In [1]:
import numpy as np
rng = np.random.default_rng()
r = rng.normal(size=(100,3))
print(r.shape)
H, edges = np.histogramdd(r, bins = (5, 8, 4))
print(H.shape, edges[0].size, edges[1].size, edges[2].size)

(100, 3)
(5, 8, 4) 6 9 5


In [1]:
import numpy as np

data = np.random.randn(1000, 3)
print(data.shape)
hist, bin_edges = np.histogramdd(data, bins=[4, 4, 4])
print(np.sum(hist))
print("ヒストグラム: ", hist)
print("ビンのエッジ: ", bin_edges)
b=np.array(bin_edges)
print(b.shape)
c=(b[0][1:] + b[0][:-1])/2
print(c)

(1000, 3)
1000.0
ヒストグラム:  [[[  0.   0.   0.   0.]
  [  0.   6.   5.   1.]
  [  0.   4.   6.   0.]
  [  0.   0.   1.   0.]]

 [[  0.  13.  16.   2.]
  [ 10.  62.  67.  11.]
  [  7.  71.  66.  10.]
  [  0.  12.  17.   1.]]

 [[  4.  14.  20.   2.]
  [ 11. 106. 103.  19.]
  [  9.  81. 105.  17.]
  [  2.  14.  18.   1.]]

 [[  0.   4.   4.   2.]
  [  3.  12.  11.   2.]
  [  1.  27.  18.   1.]
  [  0.   1.   0.   0.]]]
ビンのエッジ:  [array([-3.38217602, -1.81032146, -0.23846691,  1.33338764,  2.90524219]), array([-2.81443301, -1.37591418,  0.06260464,  1.50112347,  2.93964229]), array([-3.15909075, -1.61792408, -0.0767574 ,  1.46440927,  3.00557595])]
(3, 5)
[-2.59624874 -1.02439419  0.54746036  2.11931491]


In [30]:
import numpy as np
b=np.array([1, 2, 3])
#b[1]とb[0]の平均、b[2]とb[1]の平均...と計算する
c=[(b[1:] + b[:-1])/2]
#b[-1]は末尾の要素を取るがb[:-1]は末尾から2番目までをとる
print(b[1:], b[:-1])
print(b[-1])
print(c)

#ndarrayにe[None]とすることで外側の[]を一つ増やせる
e=np.array([[1, 2, 3], [4, 5, 6]])
print(e)
d=e[None].astype(np.uint8)
print(d)
print(type(d))

[2 3] [1 2]
3
[array([1.5, 2.5])]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


In [32]:
import math as m
print(m.sqrt(3))

1.7320508075688772


In [35]:
#*をつけることでリストを変数として関数に渡してもちゃんと各要素を引数が受け取れる
def func(x, y, z):
    return x, y, z
x, y, z = func(*[1, 2, 3])
print(x, y, z)

1 2 3


In [36]:
min(1, 2)

1

In [ ]:
thres=np.array([6, 7, 8, 9, 10])
pointsize=np.array([10, 20, 30, 40, 50])
count=7.5
#np.where(a, 条件)は条件を満たすようなaの要素の番号を取得
id=np.where(thres>=count)[0][0]
print(id)
print(pointsize[id])
print(thres[-1])
#:を使う場合は始まりが0ではなく1
print(thres[:2])

2
30
10
[6 7]


In [20]:
a=[1, 2, 3]
print(np.dot(100, a))

[100 200 300]
