In [1]:
import numpy as np
rng = np.random.default_rng()
r = rng.normal(size=(100,3))
print(r.shape)
H, edges = np.histogramdd(r, bins = (5, 8, 4))
print(H.shape, edges[0].size, edges[1].size, edges[2].size)

(100, 3)
(5, 8, 4) 6 9 5


In [7]:
import numpy as np

data = np.random.randn(1000, 3)

hist, bin_edges = np.histogramdd(data, bins=[4, 4, 4])

print("ヒストグラム: ", hist)
print("ビンのエッジ: ", bin_edges)
b=np.array(bin_edges)
print(b.shape)
c=(b[0][1:] + b[0][:-1])/2
print(c)

ヒストグラム:  [[[  0.   3.   4.   0.]
  [  2.  14.  22.   6.]
  [  2.   9.  21.   2.]
  [  1.   0.   3.   0.]]

 [[  1.  11.  22.   6.]
  [ 14.  74. 110.  27.]
  [  8.  84. 102.  27.]
  [  6.  21.  20.   2.]]

 [[  2.  12.   9.   3.]
  [  8.  66.  69.  23.]
  [  3.  48.  71.  11.]
  [  0.   6.  14.   3.]]

 [[  0.   2.   1.   1.]
  [  0.   2.   6.   0.]
  [  1.   4.   6.   2.]
  [  0.   1.   2.   0.]]]
ビンのエッジ:  [array([-3.06563261, -1.39572857,  0.27417548,  1.94407952,  3.61398356]), array([-2.87473824, -1.42894535,  0.01684755,  1.46264044,  2.90843334]), array([-3.09078972, -1.68397247, -0.27715522,  1.12966202,  2.53647927])]
(3, 5)
[-2.23068059 -0.56077654  1.1091275   2.77903154]


In [30]:
import numpy as np
b=np.array([1, 2, 3])
#b[1]とb[0]の平均、b[2]とb[1]の平均...と計算する
c=[(b[1:] + b[:-1])/2]
#b[-1]は末尾の要素を取るがb[:-1]は末尾から2番目までをとる
print(b[1:], b[:-1])
print(b[-1])
print(c)

#ndarrayにe[None]とすることで外側の[]を一つ増やせる
e=np.array([[1, 2, 3], [4, 5, 6]])
print(e)
d=e[None].astype(np.uint8)
print(d)
print(type(d))

[2 3] [1 2]
3
[array([1.5, 2.5])]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


In [32]:
import math as m
print(m.sqrt(3))

1.7320508075688772


In [35]:
#*をつけることでリストを変数として関数に渡してもちゃんと各要素を引数が受け取れる
def func(x, y, z):
    return x, y, z
x, y, z = func(*[1, 2, 3])
print(x, y, z)

1 2 3
