In [1]:
import numpy as np
rng = np.random.default_rng()
r = rng.normal(size=(100,3))
print(r.shape)
H, edges = np.histogramdd(r, bins = (5, 8, 4))
print(H.shape, edges[0].size, edges[1].size, edges[2].size)

(100, 3)
(5, 8, 4) 6 9 5


In [7]:
import numpy as np

data = np.random.randn(1000, 3)

hist, bin_edges = np.histogramdd(data, bins=[4, 4, 4])

print("ヒストグラム: ", hist)
print("ビンのエッジ: ", bin_edges)
print(np.array(bin_edges).shape)


ヒストグラム:  [[[  0.   0.   0.   0.]
  [  0.   3.   8.   1.]
  [  2.   7.   4.   1.]
  [  0.   0.   0.   0.]]

 [[  0.   2.   4.   0.]
  [  5.  54.  70.  10.]
  [  1.  65.  83.   4.]
  [  0.   5.   9.   0.]]

 [[  1.   3.  10.   1.]
  [  7. 115. 113.  11.]
  [ 10. 115. 125.  16.]
  [  2.  11.  13.   2.]]

 [[  0.   2.   0.   1.]
  [  4.  13.  35.   0.]
  [  6.  22.  18.   2.]
  [  0.   1.   3.   0.]]]
ビンのエッジ:  [array([-3.45118485, -1.88877414, -0.32636344,  1.23604727,  2.79845798]), array([-3.68050457, -1.89524057, -0.10997658,  1.67528742,  3.46055142]), array([-3.4662436 , -1.73904509, -0.01184659,  1.71535192,  3.44255042])]
(3, 5)
